### ISSUE TITLE
Suggest OS package manager

### ISSUE THREAD

**Issue by JonathonReinhart** [jimporter/patchelf-wrapper#1]
Hello. I use `patchelf` in my utility [`staticx`](https://github.com/JonathonReinhart/staticx). As I was setting up Travis for that project, a colleague pointed out `patchelf-wrapper`. Right now I have `patchelf-wrapper` in my `requirements.txt` which Travis will automatically install for Python jobs.  This made my life much easier. Thanks!

I'm looking to add my project to PyPI, and adding `patchelf-wrapper` to my `install_requires` list in `setup.py` would improve the user experience by making it easier to install. However, I'm hesitant to do so; my concern is that users who install `staticx` but don't have `patchelf` installed will automatically get a version installed from source -- even if they're on a distro that has native packages for `patchelf`.

Can you think of any way we could hand this, presumably in `patchelf-wrapper` itself? A couple rough ideas:
- Interactively confirm what's happening
- Attempt to detect the OS and run `apt-cache search` or `yum [dnf] search` to see if there exists a native package, which can be recommended (or auto-installed?)

**Comment by jimporter** [comment]
Yeah, this is one of the weirder parts of `patchelf-wrapper`. However, one of my primary goals is to make it simple for users to install PyPI packages that depend on `patchelf` (in my case, [bfg9000](https://github.com/jimporter/bfg9000)). I wanted to avoid adding prompts, since that would interrupt people, and there's not a great way to have `pip` forward options along to dependent packages to force the install (this is especially important for automation).

Theoretically, you could try to install using your OS's package manager automatically, but that still comes with a number of subtleties: first, what do you do if your OS's package manager has `patchelf`, but it's an older version than the one installed by `patchelf-wrapper`? Second, you'd need to be very careful when handling virtualenvs, since that's one of the scenarios I've tried to optimize for. There's probably a way to do this, but the `setup.py` script is already pretty scary...

In any case, the way I solved this for my own project (bfg9000) was to provide a PPA with a package that depends on the OS's `patchelf` package directly. Then I can just recommend that people use my PPA instead of installing via `pip` (unless they want to use a virtualenv, of course).

**Comment by jimporter** [comment]
Closing this based on my comment above.
